{% set version = "2.1.1" %}

package:
  name: netcdf-scm
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/netcdf-scm/netcdf-scm-{{ version }}.tar.gz
  sha256: 52995b0dc3268b8eb6b1f16c4b7c5fb5bf83fcc4e90e049653b5b00592362ec1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - cf-units >=3.0
    - cftime >=1.4
    - click
    - iris
    - numpy
    - python-dateutil
    - pymagicc >=2.0.0
    - scmdata >=0.7
    - scipy
    - tqdm
    - xarray >=0.18

test:
  imports:
    - netcdf_scm

  commands:
    - python -c "import netcdf_scm; assert netcdf_scm.__version__ == '{{ version }}'"

about:
  home: https://gitlab.com/netcdf-scm/netcdf-scm
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python wrapper for processing netCDF files for use with simple climate models
  doc_url: https://netcdf-scm.readthedocs.io/en/latest/
  dev_url: https://gitlab.com/netcdf-scm/netcdf-scm

extra:
  recipe-maintainers:
    - znicholls
    - lewisjared
