{% set version = "2.1.0" %}

package:
  name: netcdf-scm
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/netcdf-scm/netcdf-scm-{{ version }}.tar.gz
  sha256: 08fea036cd287efaf8ad901e4bf6f512e67b549a335310d5387a466d5ecf17e0

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - cftime <1.4
    - click
    - iris
    - numpy
    - python-dateutil
    - pymagicc >=2.0.0rc5
    - scmdata >=0.7
    - scipy
    - tqdm
    - xarray >=0.16.2,<0.17

test:
  imports:
    - netcdf_scm

  commands:
    - python -c "import netcdf_scm; assert netcdf_scm.__version__ == '{{ version }}'"

about:
  home: https://gitlab.com/netcdf-scm/netcdf-scm
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python wrapper for processing netCDF files for use with simple climate models
  doc_url: https://netcdf-scm.readthedocs.io/en/latest/
  dev_url: https://gitlab.com/netcdf-scm/netcdf-scm

extra:
  recipe-maintainers:
    - znicholls
    - lewisjared
